# Streamlit Configuration File
# This file configures the behavior of your Streamlit application

[theme]
# Primary accent color for interactive elements
primaryColor = "#3498db"

# Background color for the main content area
backgroundColor = "#ffffff"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#f0f2f6"

# Color used for almost all text
textColor = "#31333F"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# If true, will show a warning when you run on a publicly accessible URL
headless = true

# Enables support for Cross-Origin Resource Sharing (CORS) protection
enableCORS = false

# Port where the server will listen for browser connections
port = 8501

# Tells Streamlit to open a browser when it starts

[browser]
# Internet address where users should point their browsers in order to connect to the app
serverAddress = "0.0.0.0"

# Whether to send usage statistics to Streamlit
gatherUsageStats = false

[runner]
# Allows you to type in a variable or call a function to get the value
magicEnabled = true

# Hides streamlit-specific exception details in the browser
fastRerenderEnabled = true
